apiVersion: v1
kind: Namespace
metadata:
  name: gitops_dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: dev-sub
  namespace: gitops_dev
  annotations:
    apps.open-cluster-management.io/git-path: .
    apps.open-cluster-management.io/git-branch: stage
spec:
  channel: gitops-dev/reverse-words-cicd
  name: reverse-words-cicd-dev
  placement:
    placementRef:
      kind: PlacementRule
      name: gitops_dev
      apiGroup: apps.open-cluster-management.io
