apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: dev-sub
  namespace: dev
  annotations:
    apps.open-cluster-management.io/git-path: .
    apps.open-cluster-management.io/git-branch: prod
spec:
  channel: argocd-operator-gitops/argocd-operator-channel
  name: argocd-sub
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-argocd-to-ready-clusters
      apiGroup: apps.open-cluster-management.io
