apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: gitops_prod
  namespace: gitops_prod
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
