apiVersion: v1
kind: Namespace
metadata:
  name: gitops_prod
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gitops_sub
  namespace: gitops_prod
  annotations:
    apps.open-cluster-management.io/git-path: .
    apps.open-cluster-management.io/git-branch: stage
spec:
  channel: gitops-prod/reverse-words-cicd
  name: reverse-words-cicd-prod
  placement:
    placementRef:
      kind: PlacementRule
      name: gitops_prod
      apiGroup: apps.open-cluster-management.io
