 
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: reverse-words-application
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - reverse-words-prod
      - reverse-words-stage
