apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-to-prod-clusters
  namespace: gitops
  labels:
   app: reversewords-prod
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"

