apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-to-stage-clusters
  namespace: gitops
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels: 
      env: "stage"
  clusterReplicas: 1
