apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-to-ready-clusters
  namespace: gitops_prod
  labels:
   app: stock-gcp-managed-iowa-pro-app
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
