apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-to-ready-clusters
  namespace: gitops_stage
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
