apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: dev-sub
  namespace: gitops_dev
  labels:
    app: reverse-words-dev 
  annotations:
    apps.open-cluster-management.io/git-path: .
    apps.open-cluster-management.io/git-branch: stage
spec:
  channel: gitops/reverse-words-cicd
  name: reverse-words-cicd
  placement:
    placementRef:
      kind: PlacementRule
      name: gitops_stage
      apiGroup: apps.open-cluster-management.io
