apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: dev-sub
  namespace: gitops_prod
  labels:
    app: reverse-words-prod 
  annotations:
    apps.open-cluster-management.io/git-path: .
    apps.open-cluster-management.io/git-branch: prod
spec:
  channel: gitops/reverse-words-cicd
  name: reverse-words-cicd-dev
  placement:
    placementRef:
      kind: PlacementRule
      name: gitops_prod
      apiGroup: apps.open-cluster-management.io
